server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  application:
    name: helpdesk
  flyway:
    enabled: true
    baseline-migration: false
    location: classpath:db/migration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/helpdesk
    username: postgres
    password: postgres
